### PR TITLE
Pass deployer properties to child tasks

### LINKED ISSUE #29: Add support to propagate deployer properties to child tasks
At this time it only supports passing application properties.

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Add support for passing deployer properties into child tasks

Resolves #29

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
This requires https://github.com/spring-cloud/spring-cloud-dataflow/pull/2156

**Comment by cppwfs** [comment]
Need to add a test to ComposedTaskRunnerConfigurationWithPropertiesTests to check for deployer props.

**Comment by cppwfs** [comment]
LGTM

**Comment by cppwfs** [comment]
Rebased Squashed Merged

**Pull request closed without merging**
